### PR TITLE
Allow to use different a AddressModel for shipping and billing

### PR DESCRIPTION
**Pull request by sephii**
The setting SHOP_ADDRESS_MODEL is split in 2 settings:
SHOP_SHIPPING_ADDRESS_MODEL and SHOP_BILLING_ADDRESS_MODEL. If they're not set, they default to SHOP_ADDRESS_MODEL.

### CODE REVIEW

**Comment by rfleschenberg** [comment]
Outdated, closing. Thank you, @sephii.

**Comment by jrief** [comment]
@sephii 
Could you please give me a use case where this is important. Currently shipping and billing addresses are shared.

**Comment by rfleschenberg** [comment]
One case I can think of is where you need some legal information (e.g. a VAT ID) for the billing address, but not for the shipping address, or vice versa.

**Comment by jrief** [comment]
Good point!
Currently they share the same database table.
So we should think about creating two proxy models, one for shipping-, one for billing addresses. In default mode they both inherit from the current address model.

**Pull request closed without merging**
