### PR TITLE
Change the address model

### PR DESCRIPTION
**Pull request by rfleschenberg**
This should be more close to the current best practice for address forms.

* Rename `addressee` to `name`.
* Rename `street` to `address1`.
* Rename `supplement` to `address2`.
* Rename `location` to `city`.

These names should be closer to people's expectiations.

* Change `max_length` on these fields to 1024 characters.

Some names can be surpringly long. We should avoid recommending a database
schema that is too restrictive to deal with real-world data.

### CODE REVIEW

**Comment by jrief** [comment]
hmm...
could you please point me onto these so named "best practices" for addresses. An ISO or any kind of other norm would be great.
I tried to use the most descriptive attributes, when creating that class. Something like ``address2`` IMHO is not very descriptive.

**Comment by rfleschenberg** [comment]
I don't think there is a norm for this, at least none from which we could directly derive the fields and their  names.

This is a case where it is actually better to be less descriptive, because it means making less assumptions. For example, an address [may not include a street name](http://wiki.openstreetmap.org/wiki/Addresses#Addresses_without_street_names). So `street` is not a good name here. Users may need to to input data that is not a street name into this field. Similarly, `supplement` is often not a good term for the second line of an address (if ever -- I am pretty sure it's the wrong translation for German "Adresszusatz").

I did some research before starting to work on this and found this article:
http://www.uxmatters.com/mt/archives/2008/06/international-address-fields-in-web-forms.php 
See in particular the section "Generic formats".

The variance in international address formats is surprisingly huge. I think it makes sense for the default models to use a generic format, as recommended by the uxmatters article. This is also the format in use by amazon.com. 

Delivery services like Fedex and UPS also use a format like this, and they should know ;) Having said that, maybe it's worthwhile to include an "Address line 3" field (I took a look at the UPS worldship software, it has "address line 1", "address line 2" and "address line 3").

If integrators want to have a more specific format, for example because they only target customers from a certain country, they can of course still use their own address model.

**Comment by rfleschenberg** [comment]
Here is another source advocating this as a best practice: 

https://saasuserexperience.wordpress.com/2008/12/17/once-and-for-all-solved-international-address-fields-in-web-forms/

**Comment by jrief** [comment]
@rfleschenberg thanks for this long explanation. Yes, the link you provided convinced me to change that. Please go ahead and merge it.

**Comment by rfleschenberg** [comment]
I merged this, but we still need to manually test the example shops. I have that on my radar anyway, for reasons not related to this PR.

**Pull request merged**
