### PR TITLE
attempt to fix issue #579

### PR DESCRIPTION
**Pull request by jrief**

### CODE REVIEW

**Comment by jrief** [comment]
please wait before merging this as it breaks the API

**Comment by jrief** [comment]
@maltitco after thinking about this feature for a while, I came to the conclusion that it breaks the atomic behaviour of the Cart -> Order transaction.

If your PSP absolutely requires an order number before creating the `Order`object, then I would create a unique number and store it within the `Cart` object. Only if the payment is successful, I would reuse that number and copy it the the ``Order.number`` field.

I will therefore discard this pull request. Thanks anyway for pointing me on this problem.

**Comment by maltitco** [comment]
@jrief Order number is essential not only for the current PSP. I checked the documentation of other Polish PSP and it is similar. 

In that case, I'm waiting for your change in code to test it.

**Comment by jrief** [comment]
@maltitco 
What about using the PK of the `Cart` instance when proceeding to the payment of your PSP?
Whenever the payment was successful, you can still assign a new number to the `Order` instance.

**Comment by maltitco** [comment]
The value I give to PSP as order number must be unique and it's so much essence because it helps to check the current payment status in the PSP panel. However, this should be the order number. The PSP registers the order number and returns a token for further authorization (to check current payment status).

No matter what the payment status is (Declined, Pending, Approved), the order must be created in the store because it will make a product reservation for the customer.

**Comment by jrief** [comment]
@maltitco just discussed this issue with @rfleschenberg 
Good news for you: I will merge this PR into django-SHOP 0.10 or 1.0, since it breaks the current API.
This also means, that I have to fix the third party payment modules.

**Comment by maltitco** [comment]
@jrief Nice to hear it.

**Pull request merged**
