### PR TITLE
Atomic customer creation

### PR DESCRIPTION
**Pull request by jrief**
It seems as if customer.recognized sometimes was set outside of the transaction.
This patch should fixed it.
It also removes redundant code and the useless method ``unrecognize``.

### CODE REVIEW

**Comment by rfleschenberg** [comment]
I'm ok with merging this, but it seems to include a lot more changes than mentioned in the description. Is that on purpose?

**Comment by rfleschenberg** [comment]
Ah, I think this is because it also includes #45?

**Comment by jrief** [comment]
Please don't merge this. I'll create a smaller patch with this specific problem.

**Comment by rfleschenberg** [comment]
Obsoleted by #463.

**Pull request closed without merging**
