### PR TITLE
Latest changes from Jacob

### PR DESCRIPTION
**Pull request by rfleschenberg**

### CODE REVIEW

**Comment by jrief** [comment]
@rfleschenberg please peer review, ie. test if you can run the demo shop in Python3

**Comment by rfleschenberg** [comment]
On Python 2, the demo seems to run fine. On Python 3, I am seeing the issue below.

```
(shoptest)rene@rex /tmp/django-shop/example (develop*) $ ./manage.py migrate                 
Operations to perform:
  Synchronize unmigrated apps: clipboard, haystack, sharable, cms_bootstrap3, treebeard, adminsortable2, segmentation, sekizai, django_select2, sass_processor, django_filters, shop_stripe, djng, parler, rest_framework, staticfiles, rest_auth, optimize, django_fsm, fsm_admin, extra_fields, sitemaps, polymorphic, compressor
  Apply all migrations: auth, shop, email_auth, sites, menus, contenttypes, myshop, djangocms_text_ckeditor, cmsplugin_cascade, cms, authtoken, sessions, filer, admin, easy_thumbnails, post_office
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

(shoptest)rene@rex /tmp/django-shop/example (develop*) $ ./manage.py makemigrations --dry-run
Migrations for 'filer':
  0005_auto_20160407_2350.py:
    - Alter field subject_location on image
Migrations for 'post_office':
  0003_auto_20160407_2350.py:
    - Alter field language on emailtemplate
    - Alter field name on emailtemplate
Migrations for 'shop':
  0003_acceptconditionformpluginmodel_billingaddressformpluginmodel_breadcrumbpluginmodel_cataloglinkplugin.py:
    - Create proxy model AcceptConditionFormPluginModel
    - Create proxy model BillingAddressFormPluginModel
    - Create proxy model BreadcrumbPluginModel
    - Create proxy model CatalogLinkPluginBaseModel
    - Create proxy model CheckoutAddressPluginBaseModel
    - Create proxy model CustomerFormPluginBaseModel
    - Create proxy model CustomerFormPluginModel
    - Create proxy model DialogFormPluginBaseModel
    - Create proxy model ExtraAnnotationFormPluginModel
    - Create proxy model GuestFormPluginModel
    - Create proxy model PaymentMethodFormPluginModel
    - Create proxy model ProcessBarPluginModel
    - Create proxy model ProcessNextStepPluginModel
    - Create proxy model ProcessStepPluginModel
    - Create proxy model RequiredFormFieldsPluginModel
    - Create proxy model ShippingAddressFormPluginModel
    - Create proxy model ShippingMethodFormPluginModel
    - Create proxy model ShopAddToCartPluginModel
    - Create proxy model ShopAuthenticationPluginModel
    - Create proxy model ShopButtonPluginBaseModel
    - Create proxy model ShopCartPluginModel
    - Create proxy model ShopCatalogPluginModel
    - Create proxy model ShopLinkPluginBaseModel
    - Create proxy model ShopOrderViewsPluginModel
    - Create proxy model ShopPluginBaseModel
    - Create proxy model ShopProceedButtonModel
    - Create proxy model ShopSearchResultsPluginModel
(shoptest)rene@rex /tmp/django-shop/example (develop*) $ 
```

**Comment by jrief** [comment]
I encountered this myself. In django-filer a lot of stuff changed and apparently they forgot to add one migration. This can be ignored though.

**Comment by rfleschenberg** [comment]
Hmmm, ok, but what about the migration in django-shop? And in django-post-office?

**Comment by rfleschenberg** [comment]
Oh, I am actually seeing the same problem on Python 2. I guess this is just because the demo does not use a version of Cascade that has the latest hack to avoid migrations for proxy models. Alright. I think we can ignore this for the demo. 

Otherwise, it seems to run fine so far. I did not test it very extensively. Anyway, I think it is ok to go with a "risky" release policy at the moment.

Should we maybe release a new version of djangocms-cascade first, and then require that version in the next release of django-shop? Anyway, I am fine with merging this PR.

**Pull request merged**
