### PR TITLE
Part of package, but missing in repository

### PR DESCRIPTION
**Pull request by jrief**
unfortunately this file made it into the release 0.10.1, we therefore shall provide it

anyway, the length of the username changed in Django-1.10 to 150

### CODE REVIEW

**Comment by rfleschenberg** [comment]
Tests fail on Django 1.9. Do we still support Django 1.9, or can we ignore these failures?

**Comment by jrief** [comment]
this validator is not working on Django-1.9, hence be prepared for it.

**Comment by jrief** [comment]
my bad, did not test locally with Django-1.9

**Comment by rfleschenberg** [comment]
Let's merge if travis is green.

**Pull request merged**
