### PR TITLE
added ProductSitemap

### PR DESCRIPTION
**Pull request by vivazzi**
Added `ProductSitemap` in dependence on `SHOP_TUTORIAL`.

@rfleschenberg , you said me that:
> One hint if you're going to implement this: Watch out for n+1 queries. This can quickly become a problem > in sitemaps. `select_related` / `prefetch_related` may help.

Could you explain me about `select_related` / `prefetch_related` for this code?
I see that cms_sitemap.py:
```
class CMSSitemap(Sitemap):
    ...
    def items(self):
        all_titles = Title.objects.public().filter(
            Q(redirect='') | Q(redirect__isnull=True),
            page__login_required=False,
            page__site=Site.objects.get_current(),
        ).order_by('page__path')
        return all_titles
```
doesn't use `select_related` / `prefetch_related`.

### CODE REVIEW

**Comment by jrief** [comment]
Yes, I like this.

However the unit tests don't pass because it seems as if you import the ``ProductSitemap `` from the wrong file.

**Comment by vivazzi** [comment]
I tested by hand - it work. But I can't to reproduce the error locally. Instead of I have a ploblem: I ran test command: `py.test tests/test_money.py` and I get fails:
```
-------------- MoneySerializerTests.test_rest ---------------
Traceback (most recent call last):
  File "/home/vivazzi/projects/OTHERS/django-shop/example/tests/test_money.py", line 261, in test_rest
    self.assertDictEqual({'amount': '€ 1.23'}, serializer.data)
  File "/usr/lib/python2.7/unittest/case.py", line 835, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: {u'amount': u'\u20ac 1.23'} != {'amount': u'\u20ac 1,23'}
- {u'amount': u'\u20ac 1.23'}
?  -                    ^

+ {'amount': u'\u20ac 1,23'}
?                      ^
```

**Comment by vivazzi** [comment]
It seems I found bug.. Please one moment..

**Comment by vivazzi** [comment]
Okey - Tests is passed!

I accidentally moved sitemap.py to parent folder, but .pyc (sitemap.pyc) remained. Howbeit, locally tests did not pass. I get error:
```
AssertionError: {u'amount': u'\u20ac 1.23'} != {'amount': u'\u20ac 1,23'}
- {u'amount': u'\u20ac 1.23'}
?  -                    ^

+ {'amount': u'\u20ac 1,23'}
?                      ^
```

Jacob, do you know what's the metter?

**Comment by jrief** [comment]
@vivazzi seems to be related to the current local settings. In your locale, do you use a ``.`` or a ``,`` as decimal separator?

Presumable you can fix this using https://docs.djangoproject.com/en/1.10/topics/testing/tools/#overriding-settings

**Pull request merged**
