### PR TITLE
Fix bug with ipware.ip import get_ip

### PR DESCRIPTION
**Pull request by xggrnx**

### CODE REVIEW

**Comment by xggrnx** [comment]
In https://github.com/awesto/django-shop/blob/master/setup.py 'django-ipware', but in  https://github.com/awesto/django-shop/blob/master/tests/requirements.txt  django-ipware==2.1.0

with ipware > 2.1.0 have an error.

**Comment by jrief** [comment]
Thanks. The next time please also provide a line or two for the Changelog file.

**Comment by xggrnx** [comment]
Ok, just my first bug fix in opensource product. Ty.

**Comment by SergeyMatsiupa** [comment]
hmm... looks like this fix isn't included yet into official installation model (https://django-shop.readthedocs.io/en/1.2.2/tutorial/intro.html)

**Comment by jrief** [comment]
You changes have been released in version 1.2.3. Thanks again.

**Pull request merged**
