### PR TITLE
update cart/checkout tutorial

### PR DESCRIPTION
**Pull request by abelradac**

### CODE REVIEW

**Comment by jrief** [comment]
Thanks
Before doing double work, please always check my development branch at https://github.com/jrief/django-shop

**Comment by abelradac** [comment]
Thank you. I will keep an eye on your fork on next updates.

I have seen that you are removing SASS from project. Why?
Also i have made a branch with removed SASS since i was not able to compile libsass on CentOS in development server due to old version of C++ compiler.

**Comment by jrief** [comment]
No, I have absolutely no intention to remove SASS from the project.
BTW, if you are unable to compile SASS on your deployment platform, but able on you development, then use ``./manage.py compilescss``, build a package and deploy that. This command creates css files for offline handling.

**Comment by abelradac** [comment]
Yep, thanks. Problem was that runing pip install for djangoSHOP is crashing due to this sass package in requirements.

**Comment by jrief** [comment]
In 0.9.2 I removed this dependency - it the is optional.
You can still install django-shop from PIPy using ``pip install --no-deps django-shop`` without pulling in other dependencies.

**Pull request merged**
